# Stage 1: Build the Angular application
FROM node:20 AS build
WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Serve the application using Nginx
FROM nginx:alpine
# Update this line to match Angular 17's output path
COPY --from=build /app/dist/browser /usr/share/nginx/html
EXPOSE 80